# Generated by Django 2.0.6 on 2018-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize_image', '0002_auto_20180609_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время загрузки'),
        ),
    ]
